# Market
STOCK_MARKET = 'J'
FUTURES_MARKET = 'F'

# Account
BANKIS_GENERAL_ACCOUNT_NUMBER_SUFFIX = '01'
BANKIS_FUTURES_ACCOUNT_NUMBER_SUFFIX = '03'

# Transaction
SERVICE_CURRENT_PRICE = 'SCP'
SERVICE_CURRENT_PRICE_DAY = 'SCPD'

# Real time
SERVICE_REAL_PRICE = 'SC_R'
SERVICE_REAL_ORDER_BOOK = 'SH_R'
SERVICE_REAL_FUTURES_PRICE = 'FC_R'
SERVICE_REAL_FUTRUES_ORDER_BOOK = 'FH_R'

# Order
SERVICE_DEPOSIT_INFO = 'SATPS*1'
SERVICE_PORTFOLIO_INFO = 'SATPS*2'
SERVICE_STOCK_PRICE_MINUTE = 'PST01010300'
SERVICE_ORDER_HISTORY = 'SDOC'
SERVICE_KOSPI200_MIN = 'PUP02100200'
SERVICE_ORDER_PURCHASE = 'SCABO'
SERVICE_ORDER_SALE = 'SCAAO'

SERVICE_FUTURES_DEPOSIT_INFO = 'FOJL*1'
SERVICE_FUTURES_PORTFOLIO_INFO = 'FOJL*2'
SERVICE_FUTURES_STOCK_PRICE_MINUTE = 'PIF05010500'
SERVICE_FUTURES_TICK = 'PIF05010400'
SERVICE_FUTURES_DAY = 'KIF03020100'

# Jargons
PURCHASE = '+매수'
PURCHASE_NAKED = '매수'
SELL = '-매도'
SELL_NAKED = '매도'

# Codes
FUTURES_CODE = '101'
KOSPI200_CODE = '201'
KOSPI200_CODE_BANKIS = '2001'

ORDER_TYPE = {
    'LIMIT': '00',
    'MARKET': '01',
    'CONDITIONAL': '02',
    'MARKET PEG': '03',
    'PRIMARY PEG': '04',
    'BEFORE': '05',
    'CLOSING': '06',
    'AFTER': '07'
}
FUTURES_ORDER_TYPE = {
    'LIMIT': '01',
    'MARKET': '02',
    'CONDITIONAL': '03',
    'PRIMARY PEG': '04'
}